openapi: 3.0.0
info:
  title: Régiség Webshop API
  description: API a régiségek webshopjához, amely támogatja a termékek, rendelések és felhasználók kezelését.
  version: 1.0.0
servers:
  - url: http://backend.vm1.test
    description: VM1 backend
  - url: http://backend.vm2.test
    description: VM2 backend
paths:
  /api/products:
    get:
      summary: Termékek listázása
      description: Lekérdezi az összes terméket. Szűrés és rendezés is elérhető query paraméterek segítségével.
      operationId: products.index
      tags:
        - Termékek
      parameters:
        - name: category
          in: query
          description: Szűrés kategória alapján
          schema:
            type: string
        - name: sort_by
          in: query
          description: Rendezés mező alapján (például `name` vagy `price`)
          schema:
            type: string
        - name: order
          in: query
          description: Rendezési sorrend (`asc` vagy `desc`)
          schema:
            type: string
            enum: [asc, desc]
      responses:
        '200':
          description: A termékek listája
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
    post:
      summary: Új termék létrehozása
      description: Új termék hozzáadása az adatbázishoz (admin jogosultság szükséges).
      operationId: products.store
      tags:
        - Termékek
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Termék sikeresen létrehozva
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '422':
          description: Érvényességi hiba
  /api/products/{id}:
    get:
      summary: Egy termék adatainak lekérdezése
      description: Egy termék részletes adatainak lekérdezése az azonosítója alapján.
      operationId: products.show
      tags:
        - Termékek
      parameters:
        - name: id
          in: path
          required: true
          description: A lekérdezni kívánt termék azonosítója
          schema:
            type: integer
      responses:
        '200':
          description: A termék adatai
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: A termék nem található
    put:
      summary: Termék adatainak frissítése
      description: Egy meglévő termék adatainak frissítése (admin jogosultság szükséges).
      operationId: products.update
      tags:
        - Termékek
      parameters:
        - name: id
          in: path
          required: true
          description: A frissíteni kívánt termék azonosítója
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Termék sikeresen frissítve
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: A termék nem található
        '422':
          description: Érvényességi hiba
    delete:
      summary: Termék törlése
      description: Egy termék törlése az adatbázisból (admin jogosultság szükséges).
      operationId: products.destroy
      tags:
        - Termékek
      parameters:
        - name: id
          in: path
          required: true
          description: A törölni kívánt termék azonosítója
          schema:
            type: integer
      responses:
        '204':
          description: Termék sikeresen törölve
        '404':
          description: A termék nem található
  /api/register:
    post:
      summary: Felhasználó regisztráció
      description: Új felhasználó regisztrációja név, email és jelszó megadásával. A regisztráció során a backend validálja az adatokat.
      operationId: auth.register
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput' # Hivatkozás a UserInput sémára
      responses:
        '201':
          description: Regisztráció sikeres
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Hibás adatok
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/login:
    post:
      summary: Felhasználó bejelentkezés
      description: Bejelentkezés email/jelszó vagy név/jelszó párossal. A backend ellenőrzi, hogy a megadott adatok helyesek-e.
      operationId: auth.login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                  description: Felhasználó neve vagy email címe
                password:
                  type: string
                  description: Jelszó (minimum 8 karakter)
                  minLength: 8
              required:
                - identifier
                - password
      responses:
        '200':
          description: Bejelentkezés sikeres
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                    description: Felhasználó hitelesítési token
        '401':
          description: Hibás bejelentkezési adatok
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/logout:
    post:
      summary: Kijelentkezés
      description: Bejelentkezett felhasználó kijelentkezése (autentikáció szükséges).
      operationId: logout
      tags:
        - Felhasználók
      responses:
        '204':
          description: Sikeres kijelentkezés
components: # Csak egyszer szerepelhet a components kulcs
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: Felhasználó azonosítója
        name:
          type: string
          description: Felhasználó neve
        email:
          type: string
          format: email
          description: Felhasználó email címe
    UserInput: # Itt a UserInput definíciója
      type: object
      properties:
        name:
          type: string
          description: Felhasználó neve
          maxLength: 50
        email:
          type: string
          format: email
          description: Érvényes email cím
        password:
          type: string
          description: Jelszó (minimum 8 karakter)
          minLength: 8
      required:
        - name
        - email
        - password
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Régi Váza
        material:
          type: string
          example: Porcelán
        description: